services:
  - type: web
    name: anon-save-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: DB_URI
        sync: false
      - key: ADMINS
        value: "5451167865"
      - key: LOG_CHANNEL
        value: "-1003626735596"
      - key: PYTHON_VERSION
        value: "3.12.9"
